# Generated by Django 2.2.7 on 2019-11-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191120_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='midheading2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='midheading3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text10',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text6',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text7',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text8',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text9',
            field=models.TextField(null=True),
        ),
    ]
