# Generated by Django 2.2.7 on 2019-11-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191121_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.TextField(null=True)),
                ('p2', models.TextField(null=True)),
                ('p3', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='blog/owner/%Y/%m/%d')),
            ],
        ),
    ]
